"""Audio Replacer — FFmpeg-based audio swap for hook clips.

Given a raw clip (16:9 MP4) and a TTS audio file, this module:
  1. Finds the highest-RMS energy window within the clip matching TTS duration.
  2. Trims the video to that window (stream copy — no re-encode).
  3. Strips the original audio and muxes in the TTS audio track.

The output is a new MP4 of the same aspect ratio as the input, ready for
hook_subtitles.py to burn captions onto.
"""

import json
import subprocess
from pathlib import Path

import librosa  # already in requirements — used by the scoring engine too
import numpy as np

from utils.logger import logger


class AudioReplacerError(Exception):
    pass


def _get_duration_ffprobe(file_path: str) -> float:
    """Return duration of any media file in seconds using ffprobe."""
    cmd = [
        "ffprobe", "-v", "quiet",
        "-print_format", "json",
        "-show_format",
        str(file_path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise AudioReplacerError(f"ffprobe failed on {file_path}: {result.stderr[-200:]}")
    return float(json.loads(result.stdout).get("format", {}).get("duration", 0))


def _find_highest_energy_window(clip_path: str, target_duration: float) -> float:
    """
    Scan the clip's audio track and return the start offset (seconds) of the
    highest-RMS window of length `target_duration`.

    Falls back to 0.0 if librosa can't load the audio or if `target_duration`
    covers the whole clip.
    """
    try:
        audio, sr = librosa.load(clip_path, mono=True, sr=None, duration=None)
    except Exception as exc:
        logger.warning(f"[AUDIO_REPLACER] librosa load failed ({exc}) — using start of clip.")
        return 0.0

    clip_len_sec = len(audio) / sr
    if target_duration >= clip_len_sec:
        return 0.0  # TTS is as long as (or longer than) the clip — use whole clip

    frame_samples = int(target_duration * sr)
    step_samples  = max(1, frame_samples // 20)  # ~5% step for efficiency

    best_start_sample = 0
    best_rms          = -1.0

    for start in range(0, len(audio) - frame_samples, step_samples):
        window_audio = audio[start : start + frame_samples]
        rms = float(np.sqrt(np.mean(window_audio ** 2)))
        if rms > best_rms:
            best_rms          = rms
            best_start_sample = start

    best_start_sec = round(best_start_sample / sr, 3)
    logger.info(
        f"[AUDIO_REPLACER] Best energy window at {best_start_sec:.2f}s "
        f"(rms={best_rms:.4f}, clip={clip_len_sec:.1f}s, tts={target_duration:.1f}s)"
    )
    return best_start_sec


def replace_audio(
    clip_path: str,
    tts_audio_path: str,
    output_path: str,
) -> str:
    """
    Trim a raw clip to the highest-energy window matching TTS duration,
    then replace its audio with the TTS track.

    Args:
        clip_path      : Source raw clip (MP4, any aspect ratio).
        tts_audio_path : TTS MP3 generated by tts_engine.py.
        output_path    : Destination MP4 path.

    Returns:
        Absolute path to the output file (str).

    Raises:
        AudioReplacerError: If ffmpeg fails.
    """
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    tts_duration = _get_duration_ffprobe(tts_audio_path)
    if tts_duration <= 0:
        raise AudioReplacerError(f"TTS audio has zero duration: {tts_audio_path}")

    best_start = _find_highest_energy_window(clip_path, tts_duration)

    logger.info(
        f"[AUDIO_REPLACER] Replacing audio | "
        f"clip={Path(clip_path).name} | "
        f"tts={Path(tts_audio_path).name} ({tts_duration:.1f}s) | "
        f"trim_start={best_start:.2f}s | out={Path(output_path).name}"
    )

    cmd = [
        "ffmpeg", "-y",
        "-ss", str(best_start), "-i", clip_path,       # seek in video
        "-i", tts_audio_path,                           # TTS audio
        "-t", str(tts_duration),                        # cut to TTS length
        "-map", "0:v:0",                                # video from clip
        "-map", "1:a:0",                                # audio from TTS
        "-c:v", "copy",                                 # stream-copy video (no re-encode)
        "-c:a", "aac", "-b:a", "128k",                 # encode TTS as AAC
        "-shortest",
        str(output_path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise AudioReplacerError(
            f"FFmpeg audio replace failed (rc={result.returncode}):\n{result.stderr[-600:]}"
        )

    size_mb = Path(output_path).stat().st_size / (1024 * 1024)
    logger.info(f"[AUDIO_REPLACER] Done: {Path(output_path).name} ({size_mb:.1f} MB)")
    return str(output_path)
